# fly.toml app configuration file generated for blunderfest on 2023-06-16T07:29:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blunderfest"
primary_region = "ams"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "blunderfest.fly.dev"
  PORT = "8080"
  RELEASE_COOKIE = "a_2oMIOUZGVaXp1sCHzTLIosfR674ifuxhejKCMyzcnVY-SR6OKjgA=="
  DNS_CLUSTER_QUERY = "blunderfest.internal"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
