import Config

# For production, Phoenix typically runs behind a load balancer or reverse proxy
# (like Nginx, Caddy, or a cloud load balancer) that handles HTTPS termination.
# The release automatically enables HTTPS by reading the PORT and RAFT_ENV
# environment variables.

# Note we also include the path to a cache manifest
# containing the digested version of static files.
# This manifest is generated by the "mix phx.digest" task.
config :blunderfest_api, BlunderfestApi.Endpoint,
  url: [host: "localhost", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Initialize gettext on boot for production
config :blunderfest_api, BlunderfestApi.Gettext, null_parent_locale: "en"
