services:
  blunderfest:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    environment:
      MIX_ENV: dev
    volumes:
      - ../:/workspace/blunderfest

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "sleep infinity"
