defmodule BlunderfestWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :blunderfest

  socket "/socket", BlunderfestWeb.UserSocket, websocket: true

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :blunderfest,
    gzip: not code_reloading?,
    only: BlunderfestWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Bodies are capped well above the largest legitimate one (a 256 KB PGN
  # inside JSON); anything bigger 413s before a controller ever runs.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 512_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug BlunderfestWeb.Router
end
